### ISSUE TITLE
Colon prefix on the first event

### ISSUE THREAD

**Issue by javiercno** [dunglas/mercure#132]
Hello, 

Mercure send colon[:] on the first event received.
Example:
```
:
id: 07ef51e1-6f09-4723-b01c-5705747eae88
data: hello word

id: e6216b45-b8f9-4f5a-8e5f-1cb557430cb5
data: hello word
```

**Comment by dunglas** [comment]
It’s intended (for the heartbeat mechanism), and totally allowed by the SSE spec. A line starting with a colon is a comment and must be ignored by the client.

**Comment by javiercno** [comment]
The problem is that some clients ignore the first event because of the comment.

For example:
https://github.com/inaka/EventSource

**Comment by dunglas** [comment]
Reopening then. The best solution would be to patch those libraries (as it’s a bug). In addition, maybe be could we manage to remove this first column (it should be easy). WDYT?

**Comment by javiercno** [comment]
Why demo mercure not send colon in first event?

https://demo.mercure.rocks/

**Comment by dunglas** [comment]
Because it runs an old version of the hub 😀. I have to upgrade it.

**Comment by javiercno** [comment]
If colon prefix config set from environment variable? 
I will look for other sse clients for android and ios

**Comment by dunglas** [comment]
Not really, it's defined in the spec: https://html.spec.whatwg.org/multipage/server-sent-events.html#authoring-notes

However, there are chances that libraries with this bug also ignore some "random" events when the heartbeat mechanism is defined, because this mechanism sends a colon character every N seconds. To test this, try something like `HEARTBEAT_INTERVAL=1s ./mercure`

**Comment by javiercno** [comment]
Thanks. The problem is definitely in the client's library.
