### ISSUE TITLE
[Symfony] Not able to setup HTTPS 

### ISSUE THREAD

**Issue by Xutyr** [dunglas/mercure#175]
Hi,
I'm not able to use the mercure HUB with HTTPS whereas everything worked fine with HTTP.

**What I want to do :**
I'm trying to move my local env from HTTP to HTTPS. Regarding Mercure I updated my mercure configuration following the document but I should missed something.

**What I did :**

I update my mercure configuration as below:
```
set JWT_KEY=aVerySecretKey
set ACME_HOSTS=mysite.fr
set ALLOW_ANONYMOUS=1
set CORS_ALLOWED_ORIGINS=https://mysite.fr
.\mercure.exe
```
They I update my symfony .env file as below:
```
# See https://symfony.com/doc/current/mercure.html#configuration
MERCURE_PUBLISH_URL=https://mysite.fr/hub
# The default token is signed with the secret key: !ChangeMe!
MERCURE_JWT_KEY=aVerySecretKey
```
Regarding my JS file I set up the connection as below:
```
var handleMercure = () => {
        const url = new URL('https://mysite.fr/hub');
        url.searchParams.append('topic', "https://mysite.fr/notif");
        const eventSource = new EventSource(url, {withCredentials: true});
        eventSource.onmessage = e => {
            console.log(e);
            /* DO SOMETHING */
        }
    };
```
Following Symfony document about mercure and Grafikart video I setup a MercureCookieGenerator.php:

```
class MercureCookieGenerator
{
    /**
     * @var string
     */
    private $secret;

    public function __construct(string $secret)
    {
        $this->secret = $secret;
    }

    public function generate (User $user){
        $token = (new Builder())
            ->withClaim('mercure', ['subscribe' => ["https://mysite.fr/notif/user/{$user->getId()}"]])
            ->getToken(new Sha256(), new Key($this->secret));
        return "mercureAuthorization={$token}; Path=/hub; HttpOnly;";
    }
}
```
And finally I have my own NotificationService.php used to push to mercure a new message:
```
public function sendNotif(?User $User=null, $notif= "", $url="",$messageName="",$messageParam = [], AlertNotification $Alert=null){
        $target = [];
        if($User!==null){
            $target = ["https://mysite.fr/notif/user/{$User->getId()}"];
        }
        $update = new Update("https://mysite.fr/notif", json_encode(['url' => "${url}",'notif'=> "${notif}", 'messageName' => "${messageName}", 'messageParam' => json_encode($messageParam)]), $target);
        var_dump($update);
        $request = $this->bus->dispatch($update);
        if($Alert!==null){
            $handled = $request->last(HandledStamp::class);
            $Alert->setMercureId($handled->getResult());
        }
    }
```

**What is happening :**
When I launch the hub I only have the following line on my terminal :
```
C:\WAMP\www\mysite\mercure>.\mercure.exe
time="2019-10-08T11:08:04+02:00" level=info msg="Mercure started" protocol=https
```
Then I'm connecting to my site and got the following error:
```
dashboard:1 GET https://mysite.fr/hub?topic=https%3A%2F%2Fmysite.fr%2Fnotif net::ERR_ABORTED 404 (Not Found)
```
I got no information on the terminal which manage the Hub.

Could you help me please in order to understand what I missed?

Thanks in advanced for the help.

**Comment by 71kris** [comment]
Xutyr, I don't have any answers for you but wanted to add some comments which might/might not help to resolve your issue(s).

1. I too got it working on http, on my local Windows 7 PC (company hardware + software).
2. I failed to get Mercure working on https on Windows Server 2012R2.
3. I had a basic Symfony 4.3 project with Api-Platform bundle running on Windows IIS Server. I didn't use Docker, it won't be supported by my IT Department.
4. I cannot have it on Linux. Company is based on Windows, full stop.

Please read these comments and maybe it will save you some time discovering it (wasting time) by yourself.

1. I tried to run it on https on two instances of Windows Server 2012R2.
2. Both servers use the same wildcard SSL certificate - "subdomain1.domain.whatever" and "subdomain2.domain.whatever".
3. One server was exposed to the internet (accessible on the internet), the other on the internal network only.
4. Mercure runs by default on default 443 port, so don't try to use any other port, it won't work. It has to be 443.
5. If you have port 443 in use (for example in my case by IIS server) you won't be able to bind Mercure to 443.
6. In my case I had to stop IIS server and then Mercure was at least not complaining about the binding.
7. I still had issues and they are related to the network and Let's Encrypt.
8. I have to rely on network admins to do whatever is required (I have no access, nor I'm a sys admin).
9. It won't work on an internal network without further network configuration changes.
10. Mercure uses Let's Encrypt to generate SSL certificate on the fly. This is the problem I cannot get resolved. My IT network team would have to contact another IT network team to make required changes. See [(https://blog.heckel.io/2018/08/05/issuing-lets-encrypt-certificates-for-65000-internal-servers/)] for more info. Pay attention to "DNS Challenge" paragraph in point 1. This is quite important.
11. So, all this made me stop to implement Mercure.
12. I got a bit further with Mercure running on the server that was externally accessible on the internet but it too failed.
13. In my struggle on externally accessbile on the internet "subdomain.domain.whatever" I encountered errors flagged up by Mercure as "probably firewall settings" and "my domain" - "not in HostWhiteList".
14. I tried to use CERT_FILE and KEY_FILE instead of ACME_HOSTS with own SSL certificate but it didn't work either. Either ACME_HOSTS or CERT_FILE with KEY_FILE are required to get Mercure on https. 
14. I've googled loads and finally I gave up.
15. Having https is a must these days. If you are developing or planning to turn your application into PWA (Progressive Web Application) you have to serve it over https so having it working only on http is no good at all.

My conclusions
1. I'd love to use Mercure but the reality of my company means I simply cannot use it.
2. I'll wait another year or two and maybe by then Mercure will be mature enough to support not only Linux but also Windows, on externally accessible sub/domains and on internal only sub/domains (I wish).
3. I wish documentation was better. If you are on Linux + Docker you're kind of ok with the docs. If you are on Windows - good luck.
4. If it wasn't for Let's Encrypt I'd be probably ok with Mercure (my guess).
5. I wish Mercure server documentation was at the level of Easy Admin Bundle documentation. At the moment it is light years apart.

Maybe my findings will save time for one or two people struggling with Mercure.

**Comment by dunglas** [comment]
If you have IIS running, use it as a reverse proxy handling the TLS termination, and run the Hub in HTTP only mode behind IIS.

**Comment by dunglas** [comment]
@Xutyr are you sure the hub is up and running on `mysite.fr`? If it looks like it's not the case.

**Comment by dunglas** [comment]
Is the `mysite.fr` DNS pointing to your public IP? Keep in mind that `ACME_HOSTS` is intended for production, with a proper DNS setup etc it will usually not work in local.
Also, Let's Encrypt only work when running directly on port 443, you cannot have both the Mercure Hub and WAMP running on this port. But what you can do is to run the Hub in HTTP, on any port, and use the Apache provided by WAMP as a reverse proxy on top of the Mercure Hub: https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

**Comment by 71kris** [comment]
Hello Kevin and thank you for your reply.

I'd love to try your suggestion with reverse proxy out but I have no available dev/test server with externally accessible domain name to play with. I used one of the servers for a quick proof of concept test and I simply stopped the IIS to let Mercure bind to port 443.
That is my problem or rather the reality of the situation in my company where things become really difficult when you want something (a server, domain name etc.). I have also removed Mercure from my project.

I think Mercure is great if you can make it work. Implemented with Api-Platform and Easy Admin bundles worked great on http. Updates from Postman or from website worked great. Downside for me is that I only got it working on http. Having PWA (Progressive Web App) in mind, I'd need everything on https.

Maybe somebody else who is on Windows and reads this thread will be able to try your suggestion out (please reply to this thread and add your findings if this is you ;) ).

Thanks for your help

**Comment by Richard87** [comment]
Hi!

I have also tried migrating to production and adding https / lets-encrypt, and also facing issues...

I set up a new DigitalOcean droplet with only Docker on Ubuntu, and ran mercure...

I ran this command:
```
root@mercure:~# docker run \
>         -d -p 80:80 -p 443:443 \
>         --restart=always \
>         -v /root/public.key:/public.key \
>         -v /root/certs:/certs \
>         -e 'JWT_KEY_FILE=/public.key' \
>         -e 'JWT_ALGORITHM=RS256' \
>         -e 'ACME_HOSTS=mercure.skilnet.no' \
>         -e 'ACME_CERT_DIR=/certs' \
>         -e 'DEBUG=1' \
>         richard87/mercure:jwt-cert-file
9c102a52cf9414ff8bb839226f5fa4038a1185594d95435079e001283329f861

root@mercure:~# docker logs -f naughty_solomon 
time="2019-11-06T10:29:46Z" level=info msg="Mercure started" addr= protocol=https
2019/11/06 10:29:59 http: TLS handshake error from 82.134.58.62:52760: Get https://acme-v01.api.letsencrypt.org/directory: x509: certificate signed by unknown authority
2019/11/06 10:30:03 http: TLS handshake error from 82.134.58.62:52768: acme/autocert: missing certificate
2019/11/06 10:30:08 http: TLS handshake error from 82.134.58.62:52780: acme/autocert: missing certificate
```

Please note, at the first try, I ran it without https. and I got the welcome to mercure screen when connecting on port 80, so DNS is setup correctly :)

**Comment by doried-a-a** [comment]
I know this is a bit old, but I ran into the same issue after I started using HTTPS on my production server.  Mercure hub was always returning NOT_FOUND response and the broswser was compaining about CORS headers and other things which misled me.

After a lot of investigation, i found that I was not using a specific version for the mercure docker image, and kubernetes apparently pulled the latest image where things apparently changed.

In the latest version, the **hub url**  apparently is no longer host.name/hub, but it is something like 'https://host.name/.well-known/mercure', and the parameter MERCURE_PUBLISH_URL does not affect that anymore (please correct me if I'm wrong).

Check the updated documentation (from the beginning)
https://mercure.rocks/docs/getting-started

Hope this can help you.

(Side note: if the parameter MERCURE_PUBLISH_URL is deprecated/removed, I'd recommend mentioning that in the documentation, for people who started using an older version of mercure).

**Comment by GJoffrey** [comment]
Hello !

I'm in the same case as Xutyr and I would like to know if there is any guide to implement mercure in a prod environment with apache and Https ?

In Http I have no problems and it's very easy to configure it. But since I use Https I can not make it work...

PS : I work on a linux OS on a VPS, don't know if it's really different
