### ISSUE TITLE
mercure hub subscriber list 

### ISSUE THREAD

**Issue by benCalmette** [dunglas/mercure#246]
We arer trying to list all subscribers on a topic, unfortunately we can't use subsribtion url's or any solution to achieve this. Maybe with an access to bolt database from outside the docker container.
Someone can tell me what is subscriptionID ?

@see last comment on #62

**Comment by dunglas** [comment]
Currently, such endpoint is not available. At this point, the hub just publishes events in a specific topic when a subscriber connects or disconnects. It doesn't make the list of connected users accessible yet. The reason is that when you use a custom transport or the HA version, it will be more than one Mercure Hub, and subscribers must be aggregated across all hubs. 

One current workaround is to store this state externally (for instance in your API's database) by subscribing to these connection events and updating your DB when one of them occur.

We plan to add an endpoints to list currently connected users at some point, but it needs more work. We also plan to add support for the WebSub protocol (#100), so it will be easier for servers to subscribe to events (by receiving POST requests instead of using EventSource).
