### ISSUE TITLE
Looking for a solution to fetch user info from a new connection

### ISSUE THREAD

**Issue by josephmiller2000** [dunglas/mercure#261]
We are building a chat application using symfony and mercure.

We have achieved a lot of functions and all going smooth until we tried to get user info.

### What we are trying to achieve here:

- We are creating a massive user list at the right side of the chat room, where chatters can see the list of active chatters in the room.

- We used "Ping" method to fetch total user information redis storage and list it them on the user list.

-  This method is ok for a small chat with couple 10's of chatters. Imagine what happens when we get 1000+ users and the list keep growing more and more? each ping should receive more than 1000+ user info in each ping. This is not a right way to do it.

- So we are planning to receive each user info ( name, and user account details ) from the new connected users and add them (append them) to the user list. ==> One by One to the user list.

- So now lets go to the disconnect function, when a user logs out, or disconnected for some reason. The name of the user should be removed from the user list.

This is what we are trying to achieve, and now we planned to use websocket for this, but before using websocket, i want to give a last final try to use mercure or any other suggestive method to achieve this

Our current project demo link >> https://symfony.tamil2friends.com/guest

Any open suggestion are welcome, and we want to do make it right way and very efficient way.

**Comment by dunglas** [comment]
Did you try to use the new [subscription events](https://mercure.rocks/spec#subscription-events)? 

You can use these new events to notify all currently connected users when a new user is joining, or when a user is leaving (and update the list accordingly).
To be pass the username associated to this event to other users, be sure to include it as a [target](https://mercure.rocks/spec#terminology). I suggest to add a target such as `https://chat.example.com/user/<the-username>` in the JWT of every user, so you can easily distinguish this ID containing the username from other targets.

With this approach, there is still one remaining problem: when a new user joins, it must be able to retrieve the list of all currently connected users. What I suggest to do is to store this list in your redis or in your database. Basically, a server component must register to the subscription events, and update the list every time a user connects or disconnects. Then, you can expose this list through an API endpoint in your Symfony app.

To summarize:

**config**
1. Enable the subscription events in the Mercure Hub configuration
2. Include the username (or ID) in as a target in the Mercure JWT, also include the `https://mercure.rocks/targets/subscriptions/<your-chat-topic>` target to allow users to receive subscription/unsubscription events 

**server-side**
1. Create a script that subscribes to this event (if you want to use PHP, you can use a SSE client such as https://github.com/clue/reactphp-eventsource). This script will store the list of currently connected users in Redis, or in database.

Note: when WebSub will be supported (#100), it will be possible to expose a simple WebHook URL instead of using a ReactPHP script.

**client-side**

1. Subscribe to the chat topic, and to the subscription topic (`https://mercure.rocks/subscriptions/<your-chat-topic>/{subscriptionID}`)
2. Send a request to you API to fetch the initial list of connected users
3. Update the list every time you receive a subscription or unsubcription event

**Comment by koolay** [comment]
@dunglas 
Great project.
Is there an example about subscribe events?

**Comment by dunglas** [comment]
I'm adding an example of this technique in https://github.com/dunglas/mercure/pull/275 (written in Python, but the same idea can be implemented in any language).
