### ISSUE TITLE
Messages lost in production environment

### ISSUE THREAD

**Issue by giovannialbero1992** [dunglas/mercure#350]
Hi @dunglas, thanks for your work!
I wrote here because in production environment (Load Balancer + ECS) when I send message on a topic, i often receive 200 by mercure and message's id but in Mercure's log and by eventsource i don't see anything.
This behaviour is strange because is not always so but it happens often.

In local env with same Mercure version (v0.10.2) I use the same docker image and all messages are received by Mercure.

**Comment by dunglas** [comment]
@giovannialbero1992 so you use several Mercure Nodes in production with a load balancer in front of them right? If yes it's normal that messages are lost because the BoltDB transport don't synchronize nodes, it is only intended to work with a single Mercure server: https://mercure.rocks/docs/hub/cluster

The On Premise version is shipped with extra transport allowing to use multiple nodes.

**Comment by giovannialbero1992** [comment]
Thanks for reply.
Why this chosen? Have you plan to extend cluster feature on OS version?

**Comment by dunglas** [comment]
Here is the rationale: https://github.com/dunglas/mercure/issues/10#issuecomment-430897811

It's not planed to add these transports to the OS version, but the project is designed in a way making it possible to write your own transport and for the community to publish community-supported transports.
