### ISSUE TITLE
invalid transport DSN

### ISSUE THREAD

**Issue by FalaiTio** [dunglas/mercure#392]
Hi!!!
I'm trying to run mercure (0.10.4) in symfony (5.1) mercure bundle (0.4.0) 
All in vagrant (scotch box - Ubuntu 16.04 - Apache 2.4.18 - PHP 7.4.12)

when running:
 `JWT_KEY='aVerySecretKey' ADDR='localhost:3000' ALLOW_ANONYMOUS=1 ./bin/mercure`

I get the error:

> bolt://updates.db": invalid argument: invalid transport DSN

Can someone help me?

**Comment by campsjos** [comment]
Same here, please share if you find a solution.

**Comment by FalaiTio** [comment]
I still coldn't solve it, I followed all the documentation steps: https://symfony.com/doc/current/mercure.html#installation

But the error persist, I'm looking for a solution, when I find a post here

**Comment by campsjos** [comment]
In my case it wasn't related to Vagrant since the problem happened in a CentOS server and it was caused by the fact that i ran the command from a directory without write permission. 
Also, I remember having the same issue in my local Vagrant environment, I'm almost sure that i solved it changing the synched_folder type to 'nfs' in my Vagrantfile. 
This is how it have it now: `config.vm.synced_folder "./", "/var/www/html", :nfs => { :mount_options => ["dmode=777","fmode=777"] }`
Related: https://github.com/dunglas/mercure/issues/97#issuecomment-498226730
Hope it helps you!

**Comment by dunglas** [comment]
I changed the error message to a more explicit one (I hope) in #393.
