### ISSUE TITLE
json: cannot unmarshal string into Go struct field claims.iat of type int64

### ISSUE THREAD

**Issue by norkunas** [dunglas/mercure#404]
When building jwt with new `lcobucci/jwt` lib version I get this error.
Looking at it's source if datetime supports miliseconds then it appends it.
This lib expects datetime instances:
```
$now = new DateTimeImmutable();
$expires = $now->modify('+1 hour');       
$jwtToken = $configuration->builder()
            ->issuedAt($now)
            ->expiresAt($expires)
            ...
```

When trying to use `withClaim` manually with "iat" or "exp" it throws error: "Builder#withClaim() is meant to be used for non-registered claims, check the documentation on how to set claim "iat".

So my question is should mercure support these claims with miliseconds?

**Comment by dunglas** [comment]
This should probably be reported to the underlying JWT library we use in Mercure? WDYT? http://github.com/form3tech-oss/jwt-go

**Comment by chalasr** [comment]
As per https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-2, the jwt-go library should indeed support strings for date/time fields:
> *NumericDate* This is equivalent to the IEEE Std 1003.1,
2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
which each day is accounted for by exactly 86400 seconds, other
than that **non-integer values can be represented**. See RFC 3339
[RFC3339] for details regarding date/times in general and UTC in
particular.

I'll propose a fix there when I have some free time (but feel free to report/fix it before).
Meanwhile, here is a one-class workaround to make lcobucci/jwt v4 compatible with it: https://gist.github.com/chalasr/7fe121992bd125f2313619aff447df5f

**Comment by norkunas** [comment]
Thanks @chalasr :)

**Comment by dunglas** [comment]
Not stale

**Comment by garak** [comment]
Is there any change that fix can be backported to the legacy version (e.g. v0.10)?

**Comment by dunglas** [comment]
@garak use the "legacy" build that we provide for newer versions. It contains the fix and is compatible with the legacy configuration.
