### ISSUE TITLE
Mercure send 401 error when JWT token contain a exp field

### ISSUE THREAD

**Issue by GRUXXKi** [dunglas/mercure#522]
I've opened an issue here https://github.com/symfony/mercure-bundle/issues/56 on the Symfony Mercure bundle also.

It appears that when the JWT token contain field like "exp" in payload , it returns a 401 error.

As it could be an interesting value, maybe it should be accepted ?

mercure-bundle 0.3 and mercure server 0.11.3.

**Comment by norkunas** [comment]
Possibly related to #404 ?

**Comment by GRUXXKi** [comment]
Not sure. Is'nt it fixed now  the #404 ?

**Comment by norkunas** [comment]
Sorry, missed your mercure version :) Not sure then, for us everything works on v0.10 with simple exp as integer.

**Comment by dunglas** [comment]
This indeed has been fixed by #404.
By the way, we're in the process of migrating to `golang-jwt/jwt` instead of using our own fork (which is necessary just because of this issue). We're just waiting for https://github.com/golang-jwt/jwt/pull/15 to be merged.

Feel free to reopen if you still have the issue with the last version.

**Comment by GRUXXKi** [comment]
Yes it seems alright now !
