### ISSUE TITLE
Last message ID and multiple topics

### ISSUE THREAD

**Issue by csabavirag** [dunglas/mercure#523]
Hi,

I have the following setup. There is App-A (written in Symfony) publishes data to 3 different topics. All the messages are private and it is not balanced how the messages are published (topic1 might get 1 message while the other 2 topics get 10's of messages)

There is App-B (web frontend) subscribes to all these topics. The role of this subscriber is to display the messages received via these topics. It's not a problem to show any new message received after the subscription is made to the Hub.

The problem is with the initial content. How to display the last message of every topic when the webpage is rendered first time? Or how to do the same if the user reloads the page?

We have the Last-Event-Id acting as a pointer in the Hub's history to get any message after this point. But this ID seems to be a "global ID", which means I can not have an ID for topic1, topic2, topic3. Thus the subscriber will receive every message stored after this point, does not matter how many and associated with which topic.

Is this approach supported and I just missed in the docs?

I might store the Last-1 ID for every topic, compute the earliest one and share it via eg. redis. When I load the page, I can use this ID to load the messages and start the page with. However I feel it's not a resource friendly solution, since I have to (fetch and) skip every message but the last in every topic then. Which can even be a large data set (unless dropped due to the bolt adapter's cleanup_frequency/size settings) depending on the messages generated in other topics while one stays "untouched".

What could be the best practice here? Thanks!

**Comment by dunglas** [comment]
Hi!

The Mercure Hub acts as an [event store](https://en.wikipedia.org/wiki/Event_store), so you're right, IDs are global and there is no such concept as "IDs per topic".
When using the `Last-Event-ID` parameter, you have must an ID older than the older event you want to fetch.
By design, you'll retrieve all events published since the publication of this ID **and** matching the subscribed topic. BoltDB and the other transports used in the managed version are optimized for this use case, and it will not be resource heavy.

Best regards,
