### ISSUE TITLE
Ability for publisher to list subscribers 

### ISSUE THREAD

**Issue by mcg-web** [dunglas/mercure#62]
Hi everyone, can a publisher list the subscribers for a giving topic? This could be helpful to filter response payload and forward "only interest thing" to subscribers.

**Comment by dunglas** [comment]
This can be implemented using this process:

* store the logs of the Hub in a database such as Elasticsearch using ELK
* you be able to see how many consumers are currently connected on a given topic


But for your specific use case, I think that using targets is enough: https://github.com/dunglas/mercure/blob/master/spec/mercure.md#subscriptions

**Comment by mcg-web** [comment]
Thanks for the quick answer! I'm maybe just missing something about subscription. But lets say user 1 subscribe to a topic (http://example.com/subscription/user/1) same as user 2 to an other topic (http://example.com/subscription/user/2), taking the use case of GraphQL subscriptions users will also send queries and variables. So publish will also depend on this variables, only using target could answer to this use case?

**Comment by dunglas** [comment]
Yes

**Comment by mcg-web** [comment]
Thanks for your answer, using targets is sufficient to handle subscribers indeed. But unsubscribe can be handle only by aggregating the hub logs this could be a future enhancement (a webhook call after each unsubscribe ?)

**Comment by mcg-web** [comment]
Closing this anyway since the original issue is solved with targets :+1:

**Comment by SirSketch** [comment]
This is a follow up on the original question. In general I'm looking exactly for what has initially been asked. 

> can a publisher list the subscribers for a giving topic?

This can be very helpful for implementing a couple of things that we're currently looking at. Most simple use case would be a list of logged in users. Something in the lines of `/users/`. 

Another one would be the ability to track user activity on a given entity, eg. `/books/1` would not only send information about changes to the entity but also a list of users. This way the user can not only see changes when they happen, but also who is working on an entity. This could essentially prevent collisions.

I don't know if this is out of the scope of what mercure is trying to achieve. But since mercure knows about all of its connections it would be nice to take advantage and not implementing this with other techniques like separate web-sockets.

**Comment by Kyngo** [comment]
I totally agree with @SirSketch on that.

Such a feature would allow you to verify if it's necessary to perform an action or not depending on people using the service at the moment (like update live maps and similar things).
