### ISSUE TITLE
An issue with docker images `dunglas/mercure:v0.14.5` or `dunglas/mercure:latest`

### ISSUE THREAD

**Issue by mykbas** [dunglas/mercure#756]
Demo and steps to reproduce are here: https://github.com/mykbas/2023-03-26-mercure-image

When trying to publish via MercureHub via [IndexController.php](https://github.com/mykbas/2023-03-26-mercure-image/blob/main/src/Controller/IndexController.php) the messages are received only if `image: dunglas/mercure` is set in [docker-compose.yml](https://github.com/mykbas/2023-03-26-mercure-image/blob/main/docker-compose.yml) (set by default when adding `symfony/mercure-bundle` to the project)

When setting the exact versions `dunglas/mercure:v0.14.5` or `dunglas/mercure:latest` and publish an update via controller, the message will not be received in Mercure UI Subscribe section.

However, [PingCommand.php](https://github.com/mykbas/2023-03-26-mercure-image/blob/main/src/Command/PingCommand.php) with the same code sends messages when using any images' versions in docker-compose.yml.

Used with:

- Ubuntu 18.04
- Docker 23.0.1
- docker-compose version 1.29.1
- Symfony CLI version 5.5.2
- "symfony/mercure-bundle": "^0.3.6",

**Comment by Romaixn** [comment]
Hello! I have investigated the problem, and it seems to be caused by the Docker cache. The image may not be the correct one. I had the exact same problem on my machine, but after a few manipulations, I managed to get Mercure working again.

I ran the command `docker system prune -a` to force Docker to remove all images from my PC. Then, I was able to launch Mercure using `docker compose up --pull`, and the problem didn't occur again!

You can see the image that Docker is using by using the command `docker compose images`. It was very helpful for me during debugging.

Please let me know if it works for you. Otherwise, I recommend using Mercure with the Caddy module.
